on:
  push:
    tags:
      - "v*"

name: Release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-apple-darwin
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true

      - name: Compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}

      - name: Rename
        if: ${{ matrix.target != 'x86_64-unknown-linux-gnu' }}
        run: mv ./target/${{ matrix.target }}/release/docker-credential-ecr-login-auto ./target/${{ matrix.target }}/release/docker-credential-ecr-login-auto-${{ matrix.target }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: false
          files: |
            ./target/${{ matrix.target }}/release/docker-credential-ecr-login-auto
            ./target/${{ matrix.target }}/release/docker-credential-ecr-login-auto-${{ matrix.target }}

